import { readFileSync } from 'fs';
import path from 'path';
import * as snarkjs from 'snarkjs';
import crypto from 'crypto';

// Path to verification key - use __dirname for Node.js environment
const vKeyPath = path.join(__dirname, '../../circuits/build/verification_key.json');

/**
 * Verifies a zero-knowledge proof
 * 
 * @param publicSignals - Public inputs to the circuit
 * @param proof - The proof generated by the prover
 * @returns Promise<boolean> - Whether the proof is valid
 */
export async function verifyProof(
  publicSignals: any,
  proof: any
): Promise<boolean> {
  try {
    // Load verification key
    const vKey = JSON.parse(readFileSync(vKeyPath, 'utf-8'));
    
    // Verify the proof
    const result = await snarkjs.groth16.verify(vKey, publicSignals, proof);
    
    return result;
  } catch (error: unknown) {
    console.error('Error verifying ZKP:', error);
    return false;
  }
}

/**
 * Generate a random salt for commitment
 * 
 * @returns string - Random salt as hex string
 */
export function generateSalt(): string {
  // Use Node.js crypto module instead of browser's crypto
  const randomBytes = crypto.randomBytes(32);
  return randomBytes.toString('hex');
}

/**
 * Helper to convert string to a bigint array (for circom circuit inputs)
 * 
 * @param str - String to convert
 * @returns Array<bigint> - Array of bigints (one per character)
 */
export function stringToBigIntArray(str: string): Array<bigint> {
  return Array.from(str).map(char => BigInt(char.charCodeAt(0)));
}
